### ISSUE TITLE
Problème: Les fichiers téléchargés sont vides

### ISSUE THREAD

**Issue by Haoruiz** [istex/istex-api-harvester#11]
Bonjour, je voudrais obtenir des corpus dans l'Istex, j'ai utilisé le token généré par l'account de notre école. Il peut télécharger des fichiers, mais tous sont vides comme  dessous.

 "_error": "La ressource que vous demandez n'existe pas" .

Je l'ai utilisé comme dessous
istex-api-harvester -q telecommunication --scroll "150s" --metadata xml --size 10000 --output Download/output --bearer “*****************************"

Merci pour votre attention et aide.

**Comment by niederlec** [comment]
Bonjour,
Je suis en train d'enquêter.
Par avance, merci de ne pas diffuser votre token sur Github. Je vais être obligé de le révoquer.
Claude

**Comment by Haoruiz** [comment]
> Bonjour,
> Je suis en train d'enquêter.
> Par avance, merci de ne pas diffuser votre token sur Github. Je vais être obligé de le révoquer.
> Claude

Merci pour révoquer mon token, je l'ai oublier.

**Comment by parmentf** [comment]
À propos: tout dépend de la taille du corpus à récupérer, mais l'interface https://dl.istex.fr marchait encore très bien récemment (avec des PDF non vides, et le _fulltext_). Ça peut dépanner.

> **Remarque**: il faudrait peut-être mentionner ISTEX DL dans le README?

**Comment by niederlec** [comment]
> https://dl.istex.fr marchait encore très bien récemment (avec des PDF non vides, et le fulltext).
Quand tu dis "marchait", tu sous-entends que ce n'est plus le cas ??

**Comment by Haoruiz** [comment]
Merci, mais désolé. Je sais qu'on peut télécharger en https://dl.istex.fr/.
Je voudrais utiliser le harvest corpus selon le conseil de mon tuteur. Même si je télécharge 10 fichiers , il sont toujours vides.
Merci beaucoup pour votre attention.

**Comment by parmentf** [comment]
@niederle

**Comment by niederlec** [comment]
Il y a bien un souci avec l'API depuis la version 5.5.0, mise en production il y a 10 jours.
Il s'agit d'un problème dans la génération des URI selon que le paramètre output vaut "*" ou une valeur plus précise, "metadata" par exemple.

Requête sans problème :
https://api.istex.fr/document/?q=telecommunication&output=*&size=1

Requête provoquant le problème (regardez à la fin de la réponse de l'API) :
https://api.istex.fr/document/?q=telecommunication&output=metadata&size=1

On fait un patch dès que possible
Désolé pour le dérangement.

PS : le token que vous avez mis dans l'issue tout à l'heure est dorénavant bloqué, merci de vous en créer un nouveau

**Comment by parmentf** [comment]
Désolé d'avoir fermé l'_issue_, j'ai de trop gros doigts pour essayer de répondre depuis mon mobile.

@niederlec Non, je ne sous-entends pas que ça ne marche plus, mais que je n'ai pas vérifié depuis la semaine dernière.

**Comment by niederlec** [comment]
OK, pas de souci !!

De mon côté, j'ai patché l'API pour corriger le problème : https://api.istex.fr/document/?q=telecommunication&output=metadata&size=1 renvoie des URLs correctes maintenant

J'ai aussi mis en ligne une nouvelle version du harvester (la 2.7.1), car le paramètre `-j/--jwt` n'était pas pris en compte. À présent `-j/--jwt` remplace VRAIMENT `-B/--bearer`

Je peux enfin fermer l'issue !

@Haoruiz : merci pour le signalement de ce bug et n'héstiez pas à prévenir si vous voyez d'autres problèmes
